### ISSUE TITLE
macro_attribution.py: ValueError

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/GLAMOUR#6]
Traceback (most recent call last):

  File "C:\Users\dtchang\AppData\Local\Temp/ipykernel_14908/1130912972.py", line 1, in <module>
    attribution.plot_fp(node_idx=0)

  File "C:\Users\dtchang\Desktop\DL-KG-MM\- glamour\utils\macro_attribution.py", line 198, in plot_fp
    ax.set_yticklabels([''])

  File "C:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 75, in wrapper
    return get_method(self)(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1798, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)

  File "C:\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1721, in set_ticklabels
    "The number of FixedLocator locations"

ValueError: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (1).

**Comment by pikulsomesh** [comment]
This is being noted as a matplotlib version error, starting with 3.3.x. 
You can either change the code as suggested in the [link](https://stackoverflow.com/questions/62953704/valueerror-the-number-of-fixedlocator-locations-5-usually-from-a-call-to-set), or use 3.2.x.

**Comment by pikulsomesh** [comment]
The installation instructions in README have been updated to have the exact version number.
